# Generated by Django 3.1 on 2020-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='estado',
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.ManyToManyField(to='core.Estados'),
        ),
    ]
