# Generated by Django 3.1 on 2020-08-19 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200819_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=50, null=True)),
                ('telFixo', models.IntegerField(blank=True, null=True)),
                ('movel', models.IntegerField(blank=True, null=True)),
                ('cpf', models.IntegerField(unique=True)),
                ('cnpj', models.IntegerField(blank=True, null=True)),
                ('rua', models.CharField(blank=True, max_length=25, null=True)),
                ('bairro', models.CharField(blank=True, max_length=25, null=True)),
                ('cidade', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estados',
            name='nome',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estados',
            name='sigla',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estados'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
