# Generated by Django 3.1 on 2020-08-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200819_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='sigla',
            field=models.CharField(max_length=15),
        ),
    ]
