# Generated by Django 3.1 on 2020-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200819_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('imagem', models.ImageField(upload_to='')),
                ('tel', models.IntegerField(null=True)),
                ('descricao', models.TextField(max_length=240)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
